# Define function directory
ARG FUNCTION_DIR="/function"

FROM python:3.9.6

# set environment variables
ENV PYTHONUNBUFFERED 1
ENV USE_NNPACK=0

# Update Dependencies
RUN apt-get update -y; 
RUN apt-get upgrade -y;

# gcc compiler and opencv prerequisites
RUN apt-get -y install nano curl git build-essential libglib2.0-0 libsm6 libxext6 libxrender-dev python3 python3-pip python3-opencv wget cmake ffmpeg
RUN pip3 install --upgrade pip

# Include global arg in this stage of the build
ARG FUNCTION_DIR

# adding requirments to current directory
COPY requirements.txt ${FUNCTION_DIR}/requirements.txt
RUN pip install --target ${FUNCTION_DIR} -r ${FUNCTION_DIR}/requirements.txt

RUN git clone https://github.com/ultralytics/yolov5 --depth 1 ${FUNCTION_DIR}/yolov5
# RUN git clone git@github.com:facebookresearch/segment-anything.git --depth 1
# RUN cd segment-anything
# RUN pip install -e .
RUN pip install --target ${FUNCTION_DIR} git+https://github.com/facebookresearch/segment-anything.git

COPY . ${FUNCTION_DIR}

WORKDIR ${FUNCTION_DIR}

ENTRYPOINT [ "/usr/local/bin/python", "-m", "awslambdaric" ]
CMD [ "lambda_function.handler" ]